"""
Pydantic Schemas (Data Transfer Objects)
----------------------------------------
Defines request/response structures for API communication.
Includes validation fields for security signatures and model serialization.
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional, List
from datetime import datetime

# ==========================================
# ZONE SCHEMAS
# ==========================================
class ZoneBase(BaseModel):
    city: str

class ZoneCreate(ZoneBase):
    pass

class ZoneUpdate(BaseModel):
    city: Optional[str] = None

class Zone(ZoneBase):
    id: int
    model_config = ConfigDict(from_attributes=True)

# ==========================================
# MISURATOR (SENSOR) SCHEMAS
# ==========================================
class MisuratorBase(BaseModel):
    active: bool
    zone_id: Optional[int] = None

class MisuratorCreate(MisuratorBase):
    """
    Payload for creating a new sensor.
    Includes GPS and Security credentials.
    """
    latitude: float = Field(..., ge=-90, le=90, description="GPS Latitude")
    longitude: float = Field(..., ge=-180, le=180, description="GPS Longitude")
    # The Public Key generated by the ESP32 (Hex string)
    public_key_hex: str = Field(..., description="ECDSA Public Key (NIST256p) in Hex format")

class MisuratorUpdate(BaseModel):
    active: Optional[bool] = None
    zone_id: Optional[int] = None
    public_key_hex: Optional[str] = None

class Misurator(MisuratorBase):
    id: int
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    # We do not return the public key by default to keep responses clean,
    # but it can be added if needed.
    model_config = ConfigDict(from_attributes=True)

# ==========================================
# MISURATION (DATA POINT) SCHEMAS
# ==========================================
class MisurationCreate(BaseModel):
    """
    Payload for data ingestion.
    MUST include signature and device timestamp for verification.
    """
    value: int = Field(
        ..., 
        ge=-8192, 
        le=8192, 
        description="Vibration value. Must be within the physical constraints of the ADXL345 sensor to prevent spoofing."
    )
    misurator_id: int = Field(..., gt=0, description="The ID of the registered sensor")
    device_timestamp: int = Field(..., gt=1600000000, description="Unix timestamp of the event")
    signature_hex: str = Field(..., min_length=64, description="ECDSA NIST256p Signature")

class Misuration(BaseModel):
    id: int
    value: int
    misurator_id: int
    recorded_at: datetime

    model_config = ConfigDict(from_attributes=True)

# ==========================================
# DEVICE REGISTRATION SCHEMAS
# ==========================================
class DeviceRegisterRequest(BaseModel):
    """Payload sent by the ESP32 during its first boot."""
    public_key_hex: str = Field(..., description="The generated ECDSA public key")
    mac_address: str = Field(..., max_length=17, description="The hardware MAC address")
    enrollment_token: str = Field(..., description="The hardcoded factory enrollment token")
    latitude: float = Field(default=0.0, ge=-90, le=90)
    longitude: float = Field(default=0.0, ge=-180, le=180)
