import os
import json
import time
import redis
from sqlalchemy.orm import Session
from src.database import SessionLocal, engine
from src.models import Misuration

# Redis Config
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
redis_sync = redis.from_url(REDIS_URL, decode_responses=True)

def process_event(event: dict, db: Session):
    """Inserts a single sensor measurement into PostGIS."""
    # Note: 'device_timestamp' and 'signature_hex' are not present in the models.Misuration ORM. 
    # We only inject the fields supported by the database model. 'created_at' is auto-generated by the DB.
    new_entry = Misuration(
        value=event.get("value"),
        misurator_id=event.get("misurator_id")
    )
    db.add(new_entry)
    db.commit()

def run_worker():
    print("👷 Worker started. Listening for 'seismic_events'...")
    db = SessionLocal()
    
    while True:
        try:
            # Block until data is available in the queue
            result = redis_sync.brpop("seismic_events", timeout=0)
            if result:
                _, data = result
                event = json.loads(data)
                
                try:
                    process_event(event, db)
                    print(f"✅ Processed sensor {event.get('misurator_id')} -> {event.get('value')}")
                except Exception as e:
                    print(f"❌ DB Error: {e}. Moving to DLQ.")
                    db.rollback()
                    # Save to Dead Letter Queue for later recovery
                    redis_sync.lpush("seismic_events_dlq", data)
                    
        except Exception as e:
            print(f"❌ Redis Connection Error: {e}")
            time.sleep(2)

if __name__ == "__main__":
    # Wait for DB to be ready
    time.sleep(5) 
    run_worker()