[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_filters = esp32_exception_decoder, time

upload_port = /dev/ttyACM0  ; Set your port
monitor_port = /dev/ttyACM0 ; Set your port
upload_speed = 115200
monitor_speed = 115200

upload_protocol = esptool

# Critical hardware flash settings for the SuperMini
board_build.flash_mode = dio

upload_flags = 
    --before=no_reset
    --after=hard_reset
    --no-stub

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_dtr = 0
monitor_rts = 0

; Execute the python script to load the variables
extra_scripts = pre:extra_script.py

lib_deps =
    adafruit/Adafruit ADXL345@^1.3.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.3
    tzapu/WiFiManager
    knolleary/PubSubClient @ ^2.8