name: PR Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-validation:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic PR Check
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            backend
            frontend
            iot
            ci
            deps
            core
            fullstack
          requireScope: true